language: node_js
node_js:
  - '0.10'
before_install:
  - npm install -g gulp
  - npm install -g bower
before_script:
  - bower install
after_success:
  - './node_modules/coveralls/bin/coveralls.js < coverage/lcov.info'
